#!/usr/bin/sh

exec /usr/bin/bwrap \
	--tmpfs /tmp \
	--dev /dev \
	--proc /proc \
	--hostname npm --unshare-uts \
	--ro-bind /bin /bin \
	--ro-bind /lib /lib \
	--ro-bind /lib64 /lib64 \
	--ro-bind /usr/bin /usr/bin \
	--ro-bind /usr/lib /usr/lib \
	--ro-bind /usr/local/bin /usr/local/bin \
	--ro-bind /usr/local/lib /usr/local/lib \
	--ro-bind /etc/resolv.conf /etc/resolv.conf \
	--ro-bind /etc/profile.d /etc/profile.d \
	--ro-bind /etc/bash_completion.d /etc/bash_completion.d \
	--ro-bind /etc/ssl/certs /etc/ssl/certs \
	--ro-bind /etc/ca-certificates /etc/ca-certificates \
	--ro-bind /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt \
	--ro-bind /etc/ld.so.cache /etc/ld.so.cache \
	--ro-bind /etc/ld.so.conf /etc/ld.so.conf \
	--ro-bind /etc/ld.so.conf.d /etc/ld.so.conf.d \
	--ro-bind /etc/localtime /etc/localtime \
	--ro-bind /usr/share/terminfo /usr/share/terminfo \
	--ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
	--ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
	--ro-bind /etc/hosts /etc/hosts \
	--bind $HOME/.npm $HOME/.npm \
	--bind $HOME/.cache $HOME/.cache \
	--bind "$PWD" "$PWD" \
	/usr/bin/env npm $@

