#!/bin/sh

# Check if qdbus is installed
command -v qdbus >/dev/null || ( echo 'Please install qdbus first' >&2; exit 1 )

# The dbus endpoint to query
service='org.freedesktop.portal.Desktop'
method='/org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read'
namespace='org.freedesktop.appearance'
key='color-scheme'

# Query the dbus endpoint

# Check if query was successfully executed
if ! returnval="$(qdbus $service $method $namespace $key)"; then
	echo 'Error occured while querying qdbus' >&2
	exit 1
fi

# Return light or dark depending on query response
if [ "$returnval"  = '1' ]; then
	echo 'dark'
elif [ "$returnval" = '0' ] || [ "$returnval" = '2' ] ; then
	echo 'light'
else
	echo "Unknown query response (${returnval})" >&2
	exit 1
fi
