#!/bin/sh

mkdir portrait landscape 2>/dev/null
PORTRAITCOUNTER=0
LANDSCAPECOUNTER=0
for i in $@; do 
	echo "$i"
	DIMENSIONS=$(identify -format '%wx%h' "$i")
	WIDTH=$(echo $DIMENSIONS | cut -f1 -d 'x')
	HEIGHT=$(echo $DIMENSIONS | cut -f2 -d 'x')
	if [ $WIDTH -lt $HEIGHT ]; then 
		echo "$i --> portrait"
		ln -s "../${i}" portrait
		PORTRAITCOUNTER=$((PORTRAITCOUNTER+1))
	else
		echo "$i --> landscape"
		ln -s "../${i}" landscape
		LANDSCAPECOUNTER=$((LANDSCAPECOUNTER+1))
	fi
done
echo "$PORTRAITCOUNTER portrait images"
echo "$LANDSCAPECOUNTER landscape images"

rmdir portrait landscape 2>/dev/null
