#!/bin/sh

# Simple wrapper around pip and pip-autoremove
# This script is supposed to be used with alias so that pip3 is aliased to this script
# When run with the uninstall command it uses pip-autoremove to remove unused dependencies
# When run with other commands it uses the normal pip3

if [ "$1" == 'uninstall' ]; then
	shift 1
	env pip-autoremove $@
else
	env pip3 $@
fi

