#!/bin/sh

if [ "$USER" = 'root' ]; then
	echo 'This script can not be run as root, please execute it as a normal user!' >&2
	exit 1
fi

SUCCESS_COUNT=1
while [ $SUCCESS_COUNT -gt 0 ]; do
	SUCCESS_COUNT=0
	PACKAGES=( $(pip list -o | awk 'NR > 2 { print $1 }') )
	PACKAGES_LENGTH=${#PACKAGES}
	for PACKAGE in $PACKAGES; do
		echo "Upgrading $PACKAGE ..."
		if pip install --upgrade --user "$PACKAGE"; then
			SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
		else
			echo -e "Failed to upgrade $PACKAGE\n"
		fi
	done
done

echo '------------------------------'
echo 'Finished updating successfully'
echo '------------------------------'
