#!/bin/sh

help() {
	echo 'Rename ISO 8601 files'
	echo "Renames files with format '20[0-9]{6}' to '[0-9]{4}-[0-9]{2}-[0-9]{2}"
	echo "Usage: $0 [-f] [file...]"
	echo -e "-f\tDo not ask for confirmtaion while renaming files"
	echo -e "file\tFile to rename"
}

NO_ASK=0
while getopts "f" OPT; do
	case $OPT in
		f)
			NO_ASK=1;;
		\?)
			echo "Invalid option: -$OPTARG" >&2;;
	esac
done
shift $((OPTIND-1))

for i in "$@"; do
	if echo "$i" | grep -Pq '20\d{6}'; then
		j="$(echo "$i" | sed -r 's/(20[0-9]{2})([0-9]{2})([0-9]{2})/\1-\2-\3/')"
		if [ $NO_ASK = 1 ]; then
			mv "$i" "$j"
		else 
			read -p "Rename '$i' to '$j'? (y/n) "
			if [[ "$REPLY" =~ ^[Yy] ]]; then
				mv "$i" "$j"
			fi
		fi
	fi
done



