#!/bin/sh

IMG='/tmp/screenshot.jpg'
spectacle -b -r -n -o "$IMG" >/dev/null 2>&1
TEXT="$(zbarimg -q "$IMG")"
env rm "$IMG"
echo "$TEXT"

if [ XDG_SESSION_TYPE = 'wayland' ]; then
	echo "$TEXT" | wl-copy
elif [ XDG_SESSION_TYPE = 'x11' ]; then
	echo "$TEXT" | xclip -selection clipboard
fi

