#!/bin/sh

if [ "$USER" = 'root' ]; then
	echo 'Do not run this script as root' >&2
	exit 1
fi
if ! command -v 'kioclient5' >/dev/null; then
	echo 'kioclient5 is not installed' >&2
	exit 1
fi

for i in "$@"; do
	if [ ! -f "$i" ]; then # File does not exist
		echo "$i dooes not exist" >&2
	elif [ ! -w "$i" ]; then # File is not writeable
		echo "$i is not writeable" >&2
	else # Move the file to the trash
		echo "Trashing '$i'"
		kioclient5 move "$i" 'trash:/'
	fi
done
